# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np


In [2]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
print df.head()

   admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0


## Part 1. Frequency Tables

#### 1. Let's create a frequency table of our variables

In [48]:
# frequency table for prestige and whether or not someone was admitted

prestige_admit = pd.crosstab(index=df['prestige'], columns = df['admit'])
gre_admit = pd.crosstab(index=df['gre'], columns = df['admit'])
gpa_admit = pd.crosstab(index=df['gpa'], columns = df['admit'])

prestige_admit

admit      0   1
prestige        
1.0       28  33
2.0       95  53
3.0       93  28
4.0       55  12

## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

In [60]:
dummy_ranks = pd.get_dummies(df['prestige'], prefix="prestige_")

df_raw = pd.concat([df, dummy_ranks], axis=1)

df_raw.head()

admit    gre   gpa  prestige  prestige__1.0  prestige__2.0  prestige__3.0  \
0      0  380.0  3.61       3.0            0.0            0.0            1.0   
1      1  660.0  3.67       3.0            0.0            0.0            1.0   
2      1  800.0  4.00       1.0            1.0            0.0            0.0   
3      1  640.0  3.19       4.0            0.0            0.0            0.0   
4      0  520.0  2.93       4.0            0.0            0.0            0.0   

   prestige__4.0  
0            0.0  
1            0.0  
2            0.0  
3            1.0  
4            1.0

#### 2.2 When modeling our class variables, how many do we need? 



Answer: We only need 3, since there are 4 prestige variables.

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In [62]:
cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df_raw[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_1':])
print handCalc.head()


   admit    gre   gpa  prestige__1.0  prestige__2.0  prestige__3.0  \
0      0  380.0  3.61            0.0            0.0            1.0   
1      1  660.0  3.67            0.0            0.0            1.0   
2      1  800.0  4.00            1.0            0.0            0.0   
3      1  640.0  3.19            0.0            0.0            0.0   
4      0  520.0  2.93            0.0            0.0            0.0   

   prestige__4.0  
0            0.0  
1            0.0  
2            0.0  
3            1.0  
4            1.0  


admit    gre   gpa  prestige  prestige__1.0  prestige__2.0  prestige__3.0  \
0      0  380.0  3.61       3.0            0.0            0.0            1.0   
1      1  660.0  3.67       3.0            0.0            0.0            1.0   
2      1  800.0  4.00       1.0            1.0            0.0            0.0   
3      1  640.0  3.19       4.0            0.0            0.0            0.0   
4      0  520.0  2.93       4.0            0.0            0.0            0.0   

   prestige__4.0  
0            0.0  
1            0.0  
2            0.0  
3            1.0  
4            1.0

In [64]:
#crosstab prestige 1 admission 
# frequency table cutting prestige and whether or not someone was admitted

prestige1_admit = pd.crosstab(index=df_raw["admit"],columns=df_raw["prestige__1.0"])

prestige1_admit

prestige__1.0  0.0  1.0
admit                  
0              243   28
1               93   33

#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked college

In [73]:
prest1_admit = (33.0 / (33 + 28))

print prest1_admit

0.540983606557


#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

In [74]:
not1_admit = (93.0 / (243+93))
print not1_admit

0.276785714286


#### 3.3 Calculate the odds ratio

In [71]:
print prest1_admit / not1_admit

0.354838709677


#### 3.4 Write this finding in a sentenance: 

Answer: If you attended a tier 1 undergraduate program, you have almost double the odds of getting into undergrad.

#### 3.5 Print the cross tab for prestige_4

In [76]:
prestige4_admit = pd.crosstab(index=df_raw["admit"],columns=df_raw["prestige__4.0"])
prestige4_admit

prestige__4.0  0.0  1.0
admit                  
0              216   55
1              114   12

#### 3.6 Calculate the OR 

In [78]:
print (12.0 / (55+12)) / (114.0 / (114+216))

0.518460329929


#### 3.7 Write this finding in a sentence

Answer: If you attended a tier 4 school, there is a 50% chance odds of getting into grad school. At that level, prestige does not seem to greatly influence chances of admittance. 

## Part 4. Analysis

In [86]:
# create a clean data frame for the regression
cols_to_keep = ['admit', 'gre', 'gpa', 'prestige__1.0', 'prestige__2.0', 'prestige__3.0']
data = df_raw[cols_to_keep]
print data.head()

   admit    gre   gpa  prestige__1.0  prestige__2.0  prestige__3.0
0      0  380.0  3.61            0.0            0.0            1.0
1      1  660.0  3.67            0.0            0.0            1.0
2      1  800.0  4.00            1.0            0.0            0.0
3      1  640.0  3.19            0.0            0.0            0.0
4      0  520.0  2.93            0.0            0.0            0.0


We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [87]:
# manually add the intercept
df_raw['intercept'] = 1.0

#### 4.1 Set the covariates to a variable called train_cols

In [89]:
train_cols = ['gre', 'gpa', 'prestige__1.0', 'prestige__2.0', 'prestige__3.0']

#### 4.2 Fit the model

In [98]:
from sklearn import linear_model, cross_validation, feature_selection
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split

y = data['admit']
X = data[train_cols]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [99]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

#### 4.3 Print the summary results

In [101]:
model.coef_

array([[ 0.00240863, -0.13599629,  1.2612595 ,  0.78016578, -0.05691142]])

#### 4.4 Calculate the odds ratios of the coeffiencents and their 95% CI intervals

hint 1: np.exp(X)

hint 2: conf['OR'] = params
        
           conf.columns = ['2.5%', '97.5%', 'OR']

In [ ]:
# not really sure how to do this...

#### 4.5 Interpret the OR of Prestige_2

Answer: 

#### 4.6 Interpret the OR of GPA

Answer: 

## Part 5: Predicted probablities


As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [104]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [105]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(data['gre'].min(), data['gre'].max(), 10)
print gres
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(data['gpa'].min(), data['gpa'].max(), 10)
print gpas
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))

[ 220.          284.44444444  348.88888889  413.33333333  477.77777778
  542.22222222  606.66666667  671.11111111  735.55555556  800.        ]
[ 2.26        2.45333333  2.64666667  2.84        3.03333333  3.22666667
  3.42        3.61333333  3.80666667  4.        ]


#### 5.1 Recreate the dummy variables

In [ ]:
# recreate the dummy variables


# keep only what we need for making predictions


#### 5.2 Make predictions on the enumerated dataset

#### 5.3 Interpret findings for the last 4 observations

Answer: 

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.